name: YiXu-MagicMachine
version: '1.0'
main: com.yixu.MagicMachine
api-version: '1.13'
softdepend:
  - DecentHolograms
  - ItemsAdder

depend:
  - CustomCrops

commands:
  yixu-magicmachine:
    description: 插件主命令
    usage: /yixu-magicmachine <reload>

permissions:
  yixu-magicmachine.reload:
    description: 重载魔法机械配置文件
    default: op